---
- name: "Download filebeat's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb"
    dest: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
  register: download_filebeat
  until: download_filebeat is succeeded
- name: Install filebeat
  become: true
  apt:
    deb: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
    state: present
- name: Configure filebeat
  become: true
  template:
    mode: 0644
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat
- name: Set filebeat systemwork
  become: true
  command:
    cmd: filebeat modules enable system
    chdir: /usr/share/filebeat/bin
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enabled'
- name: load elastic index
  become: true
  command:
    cmd: filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["{{ el_instance_ip }}:9200"]'
    chdir: /usr/share/filebeat/bin
  register: filebeat_load_index
  changed_when: false
  until: filebeat_load_index is succeeded
- name: load kibana dash
  become: true
  command:
    cmd: filebeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['{{ el_instance_ip }}:9200'] -E setup.kibana.host={{ kb_instance_ip }}:5601
    chdir: /usr/share/filebeat/bin
  register: filebeat_setup
  changed_when: false
  until: filebeat_setup is succeeded
